version: '3.8'
services:
  backend:
    build:
      context: ./api
      dockerfile: src/Api/Dockerfile
    container_name: api_container
    ports:
      - "8085:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  frontend:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: angular_container
    ports:
      - "4200:80"
    depends_on:
      - backend
